<?php
/**
 * @file
 * Code for the Albatross Events feature.
 */

include_once('albatross_events.features.inc');

function albatross_events_preprocess_node(&$vars) {
  if($vars['type'] == 'event') {
    
    //add google maps picture
    if(!empty($vars['field_location'][0]) 
      && !empty($vars['field_location'][0]['thoroughfare']) 
      && !empty($vars['field_location'][0]['locality'])
      && !empty($vars['field_location'][0]['administrative_area']) ) {
      $map_url = 'http://maps.googleapis.com/maps/api/staticmap?size=150x150&sensor=false&zoom=15';

      $location = array();
      $location[] = str_replace(' ', '+', $vars['field_location'][0]['thoroughfare']);
      if(!empty($vars['field_location'][0]['premise'])) {
        $location[] = str_replace(' ', '+', $vars['field_location'][0]['premise']);
      }
      $location[] = str_replace(' ', '+', $vars['field_location'][0]['locality']);
      $location[] = str_replace(' ', '+', $vars['field_location'][0]['administrative_area']);
      
      $compiled_location = implode(',', $location);
      
      $map_url .= '&center=' . $compiled_location . '&markers=size:mid%7Ccolor:red%7C' . $compiled_location;
      
      $google_url = 'http://maps.google.com/maps?q=';
      $google_url .= str_replace(',', '+', $compiled_location);
      
      $vars['event_map'] = l(theme_image(array('path' => $map_url, 'alt' => 'event map')), $google_url, array('html' => TRUE, ));
      
    }
    
    //add day and month displays
    if(!empty($vars['node']->field_date['und'][0]['value'])) {
      $timezone = new DateTimeZone('UTC');
      $newTime = new DateTimeZone($vars['node']->field_date['und'][0]['timezone']);
      $date = new DateTime($vars['node']->field_date['und'][0]['value'], $timezone);
      $date->setTimezone( $newTime );
      $vars['event_date_month'] = $date->format('M');
      $vars['event_date_day'] = $date->format('j');
    }
    
    unset($vars['content']['links']);
  }
}
