<?php
/**
 * @file
 * Code for the CCHI Providers feature.
 */

include_once('cchi_providers.features.inc');

/**
 * Implementatation of hook_menu().
 */
/*function cchi_providers_menu() {

  $items['providers'] = array(
    'type' => MENU_CALLBACK,
    'title' => 'Find Colorado Health-care Providers',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('cchi_providers_form'),
    'access callback' => TRUE,
  );
  return $items;
}*/


/**
 * Bulk add contact form.
 */
function cchi_providers_form($form, &$form_state, $mid){
  $form = array();
  
  $form['distance'] = array(
    '#tree' => TRUE,
    '#title' => t('Where do you live?'),
  );
  
  $form['distance']['search_distance'] = array(
    '#type' => 'textfield',
    '#size' => 2,
    '#default_value' => 20,
    '#required' => TRUE,
    '#field_prefix' => t('Show all clinics within'),
    '#field_suffix' => t('miles'),
    '#weight' => 1,
    
  );
  
  $form['distance']['postal_code'] = array(
    '#type' => 'textfield',
    '#title' => t('Enter zip code'),
    '#size' => 9,
    '#weight' => 0,
    '#required' => TRUE,
  );
  
  $form['distance']['search_units'] = array(
    '#type' => 'hidden',
    '#value' => 'mile',
  );
  
  $form['kind'] = array(
    '#type' => 'checkboxes',
    '#title' => t('What kind of care are you looking for?'),
    '#description' => t('Check all that apply'),
    '#required' => TRUE,
    '#options' => array(
      'general' => t('General Health'),
      'dental' => t('Dental Health'),
      'mental' => t('Mental Health'),
      'school' => t('School Based Health Clinics '),
      'human' => t('Human Services Center '),
    ),
  );
  
  
  
  
  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Add'),
    '#weight' => 99,
  );
  
  return $form;
}


/*function cchi_providers_form_submit(&$form, &$form_state, $form_id){
  
  $kind = $form_state['values']['kind'];
  $appendix = $type = array();
  if ($kind['general']) {
    $appendix[3] = 'III';
    $type[] = 1;
    $type[] = 4;
    $type[] = 5;
  }
  if ($kind['dental']) {
    $appendix[3] = 'III';
    $type[] = 2;
  }
  if ($kind['mental']) {
    $appendix[3] = 'III';
    $type[] = 3;
  }
  if ($kind['school']) {
    $appendix[3] = 'III';
    $type[] = 6;
  }
  if ($kind['human']) {
    $appendix[2] = 'II';
  }
  
  $values = array('distance' => $form_state['values']['distance']);
  $values['appendix'] = implode('+', $appendix);
  $values['type'] = implode('+', $type);
  
  drupal_goto('providers/results', array('query' => $values));
}*/


function cchi_providers_node_presave($node) {
  if ($node->type == 'provider') {
    $type = $node->field_provider_type['und'][0]['value'];
    unset($node->field_provider_category['und']);
    
    if ($type == 1 || $type == 4 || $type == 5) {
      $node->field_provider_category['und'][]['value'] = 'general';
    }
    if ($type == 2) {
      $node->field_provider_category['und'][]['value'] = 'dental';
    }
    if ($type == 3) {
      $node->field_provider_category['und'][]['value'] = 'mental';
    }
    if ($type == 6) {
      $node->field_provider_category['und'][]['value'] = 'school';
    }
    
    if (strpos($node->field_provider_index['und'][0]['value'], 'II') !== FALSE) {
      $node->field_provider_category['und'][]['value'] = 'human';
    }
    
    //dpm($node->field_provider_category);
  }
  
}



function cchi_providers_form_views_exposed_form_alter(&$form, &$form_state, $form_id){
  if ($form['#id'] == 'views-exposed-form-providers-page') {
  
    
    $form['kind']['#type'] = 'checkboxes';
    //$form['kind']['#required'] = TRUE;
    
    unset($form['distance']['search_distance']['#title']);
    $form['distance']['search_distance']['#field_prefix'] = t('Show all clinics within');
    $form['distance']['search_distance']['#size'] = 2;
    $form['distance']['search_distance']['#field_suffix'] = t('miles.');
    //$form['distance']['search_distance']['#required'] = TRUE;
    $form['distance']['search_units'] = array(
      '#type' => 'value',
      '#value' => 'mile',
    );
    $form['distance']['postal_code']['#title'] = t('Enter zip code');
    $form['distance']['postal_code']['#size'] = 5;
    //$form['distance']['postal_code']['#required'] = TRUE;
    
    $form['submit']['#weight'] = 99;
    
    $form['appendix']['#type'] = 'value';
    $form['type']['#type'] = 'value';
  
  }
}

function cchi_providers_views_pre_render (&$view) {
  if ($view->name == 'providers') {
    if (count($view->filter['field_provider_category_value']->value) == 0) {
      unset($view->result);
    } elseif ($view->name == 'providers' && $view->current_display == 'page' && $view->result) {
      $view->header['area']->options['content'] = t('We found <strong>!num</strong> clinics matching your search. !change.', array(
        '!num' => count($view->result),
        '!change' => '<a href="#">Modify your search</a>',
      ));
    }
  } // if providers
}

/*function cchi_providers_views_pre_execute (&$view) {
  
  if ($view->name == 'providers' && $view->current_display == 'attachment_1' && !$view->exposed_raw_input['kind']) {
    dpm($view->filter);
    $view->filter['status']->value = 2;
    dpm('s');
  }
}*/
