<?php
/**
 * @file
 * TODO: Enter file description here.
 */

/**
 * Implementation of hook_block_view_alter
 */

/*function block_hover_preprocess_block(&$variables) {
  if($hover_block_arr = variable_get('block_hover_blocks')) {
    for($i = 0; $i<count($hover_block_arr); $i++) {
      if((strcmp($variables['block']->module, $hover_block_arr[$i]['module']) == 0) && (strcmp($variables['block']->delta, $hover_block_arr[$i]['delta']) == 0)){
        $variables['classes_array'][] = 'hover-block-block';
        drupal_add_css(drupal_get_path('module', 'block_hover') . '/block_hover.css');
        drupal_add_js(drupal_get_path('module', 'block_hover') . '/block_hover.js');
      }
    }
  }
}*/

function block_hover_preprocess_block(&$variables) {
  $key = 'block_hover_block_' . $variables['block']->module . '_' . $variables['block']->delta;
  if(variable_get($key, 0)){
    $variables['classes_array'][] = 'hover-block-block';
    drupal_add_css(drupal_get_path('module', 'block_hover') . '/block_hover.css');
    drupal_add_js(drupal_get_path('module', 'block_hover') . '/block_hover.js');
  }
}

function block_hover_form_alter(&$form, &$form_state, $form_id) {
  //dpm($form);
  //dpm($form_state);
  if($form['#id'] == 'block-admin-configure') {
		$key = 'block_hover_block_' . $form['module']['#value'] . '_' . $form['delta']['#value'];
		$default_value = variable_get($key, 0);
		/*$default_value = 0;
		if($hover_block_arr = variable_get('block_hover_blocks')) {
		  foreach($hover_block_arr as $item) {
		    if((strcmp($form['module']['#value'], $item['module']) == 0) && (strcmp($form['delta']['#value'], $item['delta']) == 0)){
		      $default_value = 1;
		    };
		  }
		}*/
		
		$form['settings']['block_hover'] = array(
		    '#type' => 'checkbox',
		    '#title' => t('Hover Block'),
		    '#description' => t('Turn this block into a "Hover Block" (used for mouse-over menus).  You must have a block title if this is enabled!'),
		    '#default_value' => $default_value,
		    '#weight' => -6,
		);
		$form['#validate'][] = 'block_hover_form_validate';
		$form['#submit'][] = 'block_hover_form_submit';
  //dpm(arg(0).arg(1).arg(2).arg(3).arg(4).arg(5));
  
  }
}

function block_hover_form_validate($form, &$form_state) {
  if($form_state['input']['block_hover'] && (strcmp($form_state['input']['title'], '<none>') == 0)) {
    form_set_error('title', t('In order to use the Block Hover module you must have a title'));
  }
}

/*function block_hover_form_submit($form, &$form_state) {
  $hover_block_arr = variable_get('block_hover_blocks');
  if($form_state['input']['block_hover']) {
    if($hover_block_arr) {
      foreach($hover_block_arr as $item) {
        if((strcmp($form['module']['#value'], $item['module']) != 0) || (strcmp($form['delta']['#value'], $item['delta']) != 0)){
          $hover_block_arr[] = array('module' => $form['module']['#value'], 'delta' => $form['delta']['#value']);
        };
      }
    }
    else {
      $hover_block_arr = array(array('module' => $form['module']['#value'], 'delta' => $form['delta']['#value']));
    }
  }
  else {
    if($hover_block_arr) {
      for($i = 0;$i<count($hover_block_arr);$i++) {
        if((strcmp($form['module']['#value'],$hover_block_arr[$i]['module']) == 0) && (strcmp($form['delta']['#value'],$hover_block_arr[$i]['delta']) == 0)){
          unset($hover_block_arr[$i]);
          $hover_block_arr = array_values($hover_block_arr);
          var_dump($hover_block_arr);
        }
      }
    }
  }
  variable_set('block_hover_blocks', $hover_block_arr);
}*/


function block_hover_form_submit($form, &$form_state) {
  $key = 'block_hover_block_' . $form['module']['#value'] . '_' . $form['delta']['#value'];
  $hover_block = variable_get('block_hover_block');
  if($form_state['input']['block_hover']) {
    variable_set($key, TRUE);
  }
  else {
    if($hover_block) {
      variable_del($key);
    }
  }
  
}
