<?php
/**
 * @file
 * Code for the Albatross News feature.
 */

include_once('albatross_news.features.inc');

function albatross_news_preprocess_node(&$vars) {
  if($vars['type'] == 'story') {
  
    //add day and month displays
    foreach($vars['content']['field_tags'] as $key => $value) {
      if(is_numeric($key) && is_array($value) && !empty($value['#href'])) {
        $vars['content']['field_tags'][$key]['#href'] = 'media/tag/' . $vars['content']['field_tags']['#items'][$key]['tid'];
      }
      else {
        continue;
      }
    }
  }
}
