<?php
/**
 * @file
 * Code for the hover_calendar feature.
 */

include_once('hovercalendar.features.inc');

/**
 * Implements hook_block_info().
 *
 * This hook declares what blocks are provided by the module.
 */
function hovercalendar_block_info() {

  $blocks['hovercalendar'] = array(
    'info' => t('hoverCalendar'),
    'cache' => DRUPAL_CACHE_PER_ROLE, // default
  );

  return $blocks;
}

/**
 * Implements hook_block_configure().
 *
 * This hook declares configuration options for blocks provided by this module.
 */
function hovercalendar_block_configure($delta = '') {

  $form = array();
  if ($delta == 'hovercalendar') {

    $form['source'] = array(
      '#type' => 'radios',
      '#title' => t('Source'),
      '#options' => array(
        'drupal' => 'Drupal Views. Pulls in data from the included hoverCalendar view.',
        'google' => 'Google Calendar.  Pulls in events directly from your Google Calendar feed.',
      ),      
      '#default_value' => variable_get('hovercalendar_source',  'drupal'),
    );
    
    $form['drupal_uri'] = array(
      '#type' => 'textfield',
      '#title' => t('Drupal Feed URI'),
      '#size' => 60,
      '#description' => t('The Google Calendar feed URI. Example: http://www.google.com/calendar/feeds/developer-calendar%40google.com/public/full.'),
      '#default_value' => variable_get('hovercalendar_drupal_uri',  'hovercalendar/ajax'),
      '#states' => array(
        'visible' => array(
          ':input[value="drupal"]' => array('selected' => TRUE),
        ),
      ),
    );
    
    $form['google_uri'] = array(
      '#type' => 'textfield',
      '#title' => t('Google Feed URI'),
      '#size' => 60,
      '#description' => t('The Google Calendar feed URI. Example: http://www.google.com/calendar/feeds/developer-calendar%40google.com/public/full.'),
      '#default_value' => variable_get('hovercalendar_google_uri',  ''),
      '#states' => array(
        'visible' => array(
          ':input[value="google"]' => array('selected' => TRUE),
        ),
      ),
    );
    
    
  }
  return $form;
}

/**
 * Implements hook_block_save().
 *
 * This hook declares how the configured options for a block
 * provided by this module are saved.
 */
function hovercalendar_block_save($delta = '', $edit = array()) {

  if ($delta == 'hovercalendar') {
    variable_set('hovercalendar_source', $edit['source']);
    variable_set('hovercalendar_google_uri', $edit['google_uri']);
    variable_set('hovercalendar_drupal_uri', $edit['drupal_uri']);
  }
  return;
}

/**
 * Implements hook_block_view().
 *
 * This hook generates the contents of the blocks themselves.
 */
function hovercalendar_block_view($delta = '') {
  //The $delta parameter tells us which block is being requested.
  switch ($delta) {
    case 'hovercalendar':
      $block['subject'] = t('Calendar');
      $block['content'] = hovercalendar_contents();
      break;
  }
  return $block;
}



/**
 * A block content function.
 */
function hovercalendar_contents() {
  $js = array(
    'source' => variable_get('hovercalendar_source',  'drupal'),
    'google_uri' => variable_get('hovercalendar_google_uri',  'http://www.google.com/calendar/feeds/developer-calendar%40google.com/public/full'),
    'drupal_uri' => url(variable_get('hovercalendar_drupal_uri',  'hovercalendar/ajax')),
  );
  drupal_add_js(array('hovercalendar' => $js), 'setting');
  
  drupal_add_library('system', 'ui.datepicker');
  drupal_add_css(drupal_get_path('module', 'hovercalendar') . '/hovercalendar.css');
  drupal_add_js(drupal_get_path('module', 'hovercalendar') . '/hovercalendar.js');
  drupal_add_js(drupal_get_path('module', 'hovercalendar') . '/jquery.addObject.js');
  drupal_add_js(drupal_get_path('module', 'hovercalendar') . '/jquery.hoverCalendar.js');
  //drupal_add_js('sites/all/libraries/qtip/jquery.qtip-1.0.0-rc3.min.js');

  //drupal_set_html_head('<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.5.1/jquery.min.js" type="text/javascript"></script>');

  return '<div id="hovercalendar"></div>';
}


