<?php
/**
 * @file
 * Code for the albatross_blog feature.
 */

include_once('albatross_blog.features.inc');

function albatross_blog_init() {
  /*if (strpos(request_uri(), '/blog') === 0) {
    drupal_add_js(drupal_get_path('module', 'albatross_blog') . '/js/albatross-blog.js');
  }*/
}

function albatross_blog_preprocess_node(&$vars) {
  if($vars['type'] == 'blog_post') {
 
    $vars['date'] = date('M. j, Y', $vars['created']);
    $vars['name'] = strip_tags($vars['name']);

    $href = 'node/' . $vars['nid'];
    
    //if no comments link, add one
    if(!$vars['content']['links']['comment']['#links']['comment-comments']) {
      $vars['content']['links']['comment']['#links']['comment-comments'] = array(
        'title' => $vars['comment_count'] . t(' comment') . (((int)$vars['comment_count'] === 1) ? '': 's'),
        'href' => $href,
        'attributes' => array(
          'title' => 'Jump to the first comment of this posting',
         ),
       'fragment' => 'comments',
       'html' => TRUE,
      );
      $comments = array_shift($vars['content']['links']['comment']['#links']);
      $vars['content']['links']['comment']['#links']['comment-add'] = $comments;
    }
    //change text + link
    $vars['content']['links']['comment']['#links']['comment-add']['title'] = t('Leave a comment');
    $vars['content']['links']['comment']['#links']['comment-add']['href'] = $href;
    
    $vars['content']['my_additional_field']['#prefix'] = '<div class="share-this-wrapper">';
    $vars['content']['my_additional_field']['#suffix'] = '</div>';
    //dpm($vars);
    
    //add day and month displays
    foreach($vars['content']['field_tags'] as $key => $value) {
      if(is_numeric($key) && is_array($value) && !empty($value['#href'])) {
        $vars['content']['field_tags'][$key]['#href'] = 'blog/tag/' . $vars['content']['field_tags']['#items'][$key]['tid'];
      }
      else {
        continue;
      }
    }
  }
}

/* hack since views jump menu option does not honor the base path variable */
function albatross_blog_form_ctools_jump_menu_alter(&$form, &$form_state, $form_id) {
  if(strpos($form['#action'], '/blog') === 0) {
    $link_path = '/blog';
    $tag = FALSE;
    foreach($form['jump']['#options'] as $key => $option) {
      if(stripos($option, 'Choose') > 0) {
        if(stripos($option, 'Tag') > 0) {
          $link_path = '/blog/tag';
          $tag = TRUE;
        }
        else if(stripos($option, 'Archive') > 0) {
          $link_path = '/blog/archive';
        }
        continue;
      }
      if(!strpos($option, 'No value')) {
        if($tag) {
          $value_arr = explode(' ', $option);
          $term = taxonomy_term_load($value_arr[0]);
          $value = $term->name . ' ' . $value_arr[1];
        }
        else {
          $value = $option;
        }
        $form['jump']['#options'][$link_path . substr($key, strripos($key, '/'))] = $value;
      }
      unset($form['jump']['#options'][$key]);
    }
  }
}
